Repository bskinn/sphobjinv, pull requests merged in 2025-05, with the labels that each got.

#315 Skip more characters in test_name_lead_chars for Sphinx 8.2
  CHANGELOG.md
  tests/test_valid_objects.py
  tox.ini
Labels: type: maintenance :wrench:, area: tests :stethoscope:, pr: merge ready :+1:, bump: upkeep :lady_beetle:

#319 Merge v2.3.1.3 release branch back into `main`
  CHANGELOG.md
  LICENSE.txt
  README.md
  conftest.py
  doc/source/conf.py
  setup.py
  src/sphobjinv/__init__.py
  src/sphobjinv/__main__.py
  src/sphobjinv/_vendored/__init__.py
  src/sphobjinv/_vendored/fuzzywuzzy/__init__.py
  src/sphobjinv/cli/__init__.py
  src/sphobjinv/cli/convert.py
  src/sphobjinv/cli/core.py
  src/sphobjinv/cli/load.py
  src/sphobjinv/cli/parser.py
  src/sphobjinv/cli/paths.py
  src/sphobjinv/cli/suggest.py
  src/sphobjinv/cli/ui.py
  src/sphobjinv/cli/write.py
  src/sphobjinv/data.py
  src/sphobjinv/enum.py
  src/sphobjinv/error.py
  src/sphobjinv/fileops.py
  src/sphobjinv/inventory.py
  src/sphobjinv/re.py
  src/sphobjinv/schema.py
  src/sphobjinv/version.py
  src/sphobjinv/zlib.py
  tests/test_api_fail.py
  tests/test_api_good.py
  tests/test_api_good_nonlocal.py
  tests/test_cli.py
  tests/test_cli_nonlocal.py
  tests/test_fixture.py
  tests/test_flake8_ext.py
  tests/test_intersphinx.py
  tests/test_valid_objects.py
  tox.ini
Labels: type: maintenance :wrench:

#320 Fix GitHub badge
  .github/workflows/all_core_tests.yml
  CHANGELOG.md
  README.md
Labels: type: maintenance :wrench:, pr: merge ready :+1:, area: meta :brain:, bump: upkeep :lady_beetle:
